sudo: required

language: java

install: ant
jdk: oraclejdk7

services:
  - docker
  - postgresql
script:
   ant todo
after_success:
  - docker build -t adempiere .
notifications:
  email:
    - desarrollo@erpcya.com
