language: 
  java

addons:
  postgresql: "9.4"
  
services:
  - postgresql
  
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.4
  
before_script:
  - psql -c 'CREATE USER adempiere PASSWORD ''1234'';'
  - psql -c 'ALTE ROLE adempiere WITH CREATEDB LOGIN;'
  - psql -c 'create database adempiere_380 WITH OWNER adempiere;' -U postgres
  mkdir /opt/Apps/

script: 
  ant todo
  
