sudo: required

language: java

install: ant
jdk: oraclejdk7

script:
   ant todo
addons:
    apt:
        packages:
            - sshpass
after_success:
  - export SSHPASS=$PASS
   sshpass -e scp /home/travis/build/erpcya/adempiere_370_Fork/install/build/Adempiere_370LTS.tar.gz $USER@$HOST:$TOPATH
   sshpass -e ssh $USER@$HOST $TOPATH/deploy.sh
    
notifications:
  email:
     desarrollo@erpcya.com
